# don't care about Pods
excluded:
  - Pods

# optional rules added
opt_in_rules:
  - explicit_init
  - overridden_super_call
  - private_outlet
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call

# disable rules
disabled_rules:
  - trailing_whitespace
  - vertical_parameter_alignment
  - identifier_name
  - switch_case_alignment
  - legacy_constructor
  - multiple_closures_with_trailing_closure

# options

file_length:
  warning: 500
  error: 1200

force_cast:
  severity: warning

vertical_whitespace:
  max_empty_lines: 3

line_length:
  warning: 180
  ignores_function_declarations: true
  ignores_comments: true
