# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyJogs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  # network debug
  pod 'Bagel', '~> 1.3'

  #asset management
  pod 'SwiftGen', '~> 5.2'

  #UI
  pod 'lottie-ios', '~> 3.0.3' ## Animation

  #Swift norm rules fornatting
  pod 'SwiftLint', '~> 0.31.0'

  # Pods for MyJogs

  target 'MyJogsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyJogsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
